-- ===============================================================================================================
-- SOLVED CHALLENGE
-- ===============================================================================================================
USE sakila;
-- ===============================================================================================================
-- 1. List the number of films per category.
-- view the table film_category
SELECT * FROM film_category;
-- list nbr_films per category_id
SELECT
	category_id,
	COUNT(DISTINCT film_id) AS nbr_films
FROM film_category 
GROUP BY category_id;
-- ===============================================================================================================
-- 2. Retrieve the store ID, city, and country for each store.
-- store_id FROM store table
-- city FROM city table
-- country FROM country table
-- different tables sources
-- ----------------------------------------------------
-- store table
SELECT * FROM store;
-- store columns
SHOW COLUMNS FROM store;
-- --------------------------------
-- address table
SELECT * FROM address;
-- address columns
SHOW COLUMNS FROM address;
-- --------------------------------
-- city table
SELECT * FROM city;
-- city columns
SHOW COLUMNS FROM city;
-- --------------------------------
-- country table
SELECT * FROM country;
-- country columns
SHOW COLUMNS FROM country;
-- ----------------------------------------------------------------------
-- ----------------------------------------------------------------------
SELECT 
	store.store_id, -- store_id from store table
    -- address.address, -- address from address table
	city.city, -- city from city table
    country.country -- country from country table
FROM store
JOIN address ON store.address_id = address.address_id -- store and address tables share address_id to collect address
JOIN city ON address.city_id = city.city_id -- address and city tables share city_id to collect city
JOIN country ON city.country_id = country.country_id; -- city and country tables share country_id to collect country
-- ======================================================================================================================
-- 3.  Calculate the total revenue generated by each store in dollars.
SELECT * FROM store;
SELECT * FROM payment;
-- ----------------------------------------------------------------------------------------------------------
SELECT
	store.store_id, -- store_id from store table
    customer.customer_id, -- customer_id from customer table
	rental.rental_id, -- rental_id from rental table
    payment.amount -- amount from payment table
FROM store
JOIN customer ON customer.store_id = store.store_id -- customer and store tables share store_id
JOIN rental ON rental.customer_id = customer.customer_id -- rental and customer tables share customer_id
JOIN payment ON payment.rental_id = rental.rental_id; -- payment and rental tables share rental_id
-- ----------------------------------------------------------------------------------------------------------
-- method 01: from store table
SELECT
    store.store_id,
    SUM(payment.amount) AS total_revenue
FROM store
JOIN customer ON customer.store_id = store.store_id
JOIN rental ON rental.customer_id = customer.customer_id
JOIN payment ON payment.rental_id = rental.rental_id
GROUP BY store.store_id;
-- ---------------------------------------------------------------------------------------------------
-- method 02: from payment table
SELECT 
	store.store_id, -- store_id from store table
    SUM(payment.amount) AS total_revenue -- sum of all amount from payment table AS total_revenue
FROM payment
JOIN staff ON payment.staff_id = staff.staff_id -- payment and staff tables share staff_id
JOIN store ON staff.store_id = store.store_id -- staff and store tables share store_id
GROUP BY store.store_id;
-- ===============================================================================================================
-- 4.  Determine the average running time of films for each category.
-- --------------------------------
-- film table & columns
SELECT * FROM film;
SHOW COLUMNS FROM film;
-- --------------------------------
-- film_category table & columns
SELECT * FROM film_category;
SHOW COLUMNS FROM film_category;
-- ---------------------------------------------
-- film and film_category share film_id column
-- length from FROM table
-- category_id FROM film_category table
-- ---------------------------------------------
SELECT
    film_category.category_id, -- category_id from film_category table
    AVG(film.length) AS avg_run_time
FROM film_category
JOIN film ON film_category.film_id = film.film_id -- film_category and film share film_id
GROUP BY film_category.category_id; -- group by category_id
-- ---------------------------------------------------------------------------------------------------------------
-- show result in hours and minutes
SELECT
    film_category.category_id,
    CONCAT(FLOOR(AVG(film.length) / 60), 'h ', MOD(ROUND(AVG(film.length)), 60), 'm') AS avg_run_time
FROM film_category
JOIN film ON film_category.film_id = film.film_id
GROUP BY film_category.category_id;
-- ===============================================================================================================
-- ===============================================================================================================
-- BONUS CHALLENGE
-- ===============================================================================================================
-- ===============================================================================================================
-- 5.  Identify the film categories with the longest average running time.
-- --------------------------------
-- film table & columns
SELECT * FROM film;
SHOW COLUMNS FROM film;
-- --------------------------------
-- film_category table & columns
SELECT * FROM film_category;
SHOW COLUMNS FROM film_category;
-- ---------------------------------------------
-- film and film_category share film_id column
-- length from FROM table
-- category_id FROM film_category table
-- ---------------------------------------------
SELECT
    film_category.category_id, -- category_id from film_category table
    AVG(film.length) AS avg_run_time
FROM film_category
JOIN film ON film_category.film_id = film.film_id -- film_category and film share film_id
GROUP BY film_category.category_id  -- group by category_id
ORDER BY avg_run_time DESC; -- order by avg_run_time in descending order
-- LIMIT 5; -- top 5 categories -- top five categories are 15, 10, 9, 7, 5
-- ===============================================================================================================
-- 6.  Display the top 10 most frequently rented movies in descending order.
-- --------------------------------
-- film table & columns
SELECT * FROM film;
SHOW COLUMNS FROM film;
-- --------------------------------
-- rental table & columns
SELECT * FROM rental;
SHOW COLUMNS FROM rental; 
-- ---------------------------------------------------------------
-- film and inventory tables share film_id column
-- inventory and rental share inventory_id column
-- ----------------------------------------------------------------
SELECT
    film.film_id, -- film_id from film table
    film.title, -- title from film table
    COUNT(rental.rental_id) AS rental_frequency -- we count how many times rental_id from rental
FROM film
JOIN inventory ON film.film_id = inventory.film_id -- film and inventory tables share film_id
JOIN rental ON inventory.inventory_id = rental.inventory_id -- inventory and rental share inventory_id
GROUP BY film.film_id, film.title -- group by film_id and title 
ORDER BY rental_frequency DESC -- order descending
LIMIT 10;
-- ===============================================================================================================
-- 7. Determine if "Academy Dinosaur" can be rented from Store 1.
-- --------------------------------
-- film table & columns
SELECT * FROM film;
SHOW COLUMNS FROM film;
-- --------------------------------
-- inventory table & columns
SELECT * FROM inventory;
SHOW COLUMNS FROM inventory;
-- --------------------------------
-- store table & columns
SELECT * FROM store;
SHOW COLUMNS FROM store;
-- ---------------------------------------------------------------
-- film and inventory tables share film_id column
-- store and inventory share store_id column
-- ----------------------------------------------------------------
-- film table & columns
SELECT title FROM film;
-- ---------------------------------------------------------------- 
-- WHERE title = 'Academy Dinosaur' AND store_id = 1 THEN status='YES, it CAN be rented'
-- ELSE status='NO, it CANNOT be rented'
-- ----------------------------------------------------------------------------------------------.
SELECT 
    film.film_id,
    film.title,
    CASE 
        WHEN inventory.inventory_id IS NOT NULL THEN 'YES, it CAN be rented'
        ELSE 'NO, it CANNOT be rented'
    END AS rental_status
FROM film
LEFT JOIN inventory
    ON film.film_id = inventory.film_id AND inventory.store_id = 1;
-- ----------------------------------------------------------------------------------------------
SELECT 
    film.film_id,
    film.title,
    CASE 
        WHEN COUNT(inventory.inventory_id) > 0 THEN 'YES, it CAN be rented'
        ELSE 'NO, it CANNOT be rented'
    END AS rental_status
FROM film
LEFT JOIN inventory
    ON film.film_id = inventory.film_id AND inventory.store_id = 1
GROUP BY film.film_id, film.title;
-- ----------------------------------------------------------------------------------------------
SELECT 
    CASE 
        WHEN COUNT(*) > 0 THEN 'YES, it CAN be rented'
        ELSE 'NO, it CANNOT be rented'
    END AS rental_status
FROM inventory
JOIN film ON inventory.film_id = film.film_id -- film and inventory tables share film_id
WHERE film.title = 'Academy Dinosaur' AND inventory.store_id = 1;
-- ===============================================================================================================
-- 8. Provide a list of all distinct film titles, along with their availability status in the inventory. 
-- Include a column indicating whether each title is 'Available' or 'NOT available.' 
-- Note that there are 42 titles that are not in the inventory,
	-- and this information can be obtained using a `CASE` statement combined with `IFNULL`."
-- ---------------------------------------------------------------------------------------------------------------
SELECT
    film.film_id,
    film.title,
    CASE 
        WHEN COUNT(inventory.inventory_id) > 0 THEN 'Available'
        ELSE 'NOT available'
    END AS availability_status
FROM film
LEFT JOIN inventory
    ON film.film_id = inventory.film_id
GROUP BY film.film_id, film.title
ORDER BY film.title;
-- ----------------------------------------------------------------------
SELECT
    film.film_id,
    film.title,
    CASE 
        WHEN IFNULL(COUNT(inventory.inventory_id), 0) > 0 THEN 'Available'
        ELSE 'NOT available'
    END AS availability_status
FROM film
LEFT JOIN inventory ON film.film_id = inventory.film_id
GROUP BY film.film_id, film.title
ORDER BY film.title;
-- ---------------------------------------------------------------------------
-- verifying that there are only 42
SELECT COUNT(*) AS nbr_non_available_films
FROM film
LEFT JOIN inventory ON film.film_id = inventory.film_id
WHERE inventory.inventory_id IS NULL;
-- ===============================================================================================================
